name: E2E Tests

on:
  workflow_dispatch:
    inputs:
      next_api_domain:
        description: "Next.js + ElysiaJS domain for E2E tests"
        required: false
        default: "https://vercel-bun-nine.vercel.app"
        type: string
      vanilla_api_domain:
        description: "Vanilla domain for E2E tests"
        required: false
        default: "https://vercel-bun-bench.vercel.app"
        type: string

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: cd example && bun install && cd ../bench && bun install

      - name: Run E2E tests
        run: bun run e2e
        env:
          E2E_NEXT_API_DOMAIN: ${{ inputs.next_api_domain || 'https://vercel-bun-nine.vercel.app' }}
          E2E_VANILLA_API_DOMAIN: ${{ inputs.vanilla_api_domain || 'https://vercel-bun-bench.vercel.app' }}
